### ISSUE TITLE
[k8s v1.19.2] cannot get resource "namespaces" in API group "" in the namespace "pods"

### ISSUE THREAD

**Issue by Incrementing** [morphy2k/k8s-mongo-sidecar#81]
Testing out k8s 1.19.2 and getting the below error, worked on a previous version of kubernetes. 
Thanks in advance for any help.
```
$ logs mongo-0 mongo-sidecar

> k8s-mongo-sidecar@0.4.2 start /opt/k8s-mongo-sidecar
> node src/index.js

Using mongo port: 27017
Starting up k8s-mongo-sidecar
The cluster domain 'cluster.local' was successfully verified.
Error in workloop: Error: namespaces "pods" is forbidden: User "system:serviceaccount:default:mongo" cannot get resource "namespaces" in API group "" in the namespace "pods"
    at /opt/k8s-mongo-sidecar/node_modules/kubernetes-client/backends/request/client.js:231:25
    at Request._callback (/opt/k8s-mongo-sidecar/node_modules/kubernetes-client/backends/request/client.js:168:14)
    at Request.self.callback (/opt/k8s-mongo-sidecar/node_modules/request/request.js:185:22)
    at Request.emit (events.js:310:20)
    at Request.<anonymous> (/opt/k8s-mongo-sidecar/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:310:20)
    at IncomingMessage.<anonymous> (/opt/k8s-mongo-sidecar/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:416:28)
    at IncomingMessage.emit (events.js:322:22)
    at endReadableNT (_stream_readable.js:1187:12) {
  code: 403,
  statusCode: 403
}
```

**Comment by Incrementing** [comment]
`process.env.KUBERNETES_NAMESPACE` was undefined, setting it to default resolved the issue.
